[package]
name = "sock"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"

[dependencies]
cli-table = "0.4.7"
# egui = "0.22.0"
# nohash-hasher = "0.2.0"
# num-traits = "0.2.15"
rayon = "1.7.0"
rustc-hash = "1.1.0"
strum = { version = "0.25.0", features = ["derive"]}
# termion = "2.0.1"
