[package]
name = "sock"
version = "0.1.0"
edition = "2021"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

[profile.release]
debug = true

[dependencies]
cli-table = "0.4.7"
termion = "2.0.1"
