[package]
name = "sock"
version = "0.1.0"
edition = "2021"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Clink-arg=-Wl,--no-rosegment"]

[profile.release]
debug = true

[dependencies]
cli-table = "0.4.7"
nohash-hasher = "0.2.0"
num-traits = "0.2.15"
rayon = "1.7.0"
rustc-hash = "1.1.0"
termion = "2.0.1"
